# Generated by Django 2.2.1 on 2019-08-25 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schoolrool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('alread_name', models.CharField(default='无', max_length=15)),
                ('IDcard', models.CharField(max_length=18)),
                ('address', models.CharField(max_length=150)),
                ('is_child', models.BooleanField(default=False)),
                ('is_leftover_child', models.BooleanField(default=False)),
                ('is_healdy', models.BooleanField(default=True)),
                ('entrance_date', models.DateTimeField(auto_now_add=True)),
                ('entrance_go', models.CharField(max_length=150)),
                ('how_go_school', models.CharField(max_length=150)),
                ('is_disable', models.BooleanField(default=False)),
                ('country_ID', models.CharField(default='', max_length=20)),
                ('province_ID', models.CharField(default='', max_length=20)),
                ('by_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.Bytype')),
                ('class_bj', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.Class_bj')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.Grade')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.Nation')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.School')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.Sex')),
            ],
        ),
        migrations.CreateModel(
            name='Familymembertwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name_two', models.CharField(max_length=15)),
                ('member_address_two', models.CharField(max_length=150)),
                ('member_phtwo_two', models.CharField(max_length=11)),
                ('is_guardian_two', models.BooleanField(default=True)),
                ('member_idcard_two', models.CharField(max_length=18)),
                ('member_job_two', models.CharField(max_length=150)),
                ('member_duty_two', models.CharField(max_length=150)),
                ('member_nation_two', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.Nation')),
                ('member_ralation_two', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.Ralation')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='schoolrool.Schoolrool')),
            ],
        ),
        migrations.CreateModel(
            name='Familymemberone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name_one', models.CharField(max_length=15)),
                ('member_address_one', models.CharField(max_length=150)),
                ('member_phone_one', models.CharField(max_length=11)),
                ('is_guardian_one', models.BooleanField(default=True)),
                ('member_idcard_one', models.CharField(max_length=18)),
                ('member_job_one', models.CharField(max_length=150)),
                ('member_duty_one', models.CharField(max_length=150)),
                ('member_nation_one', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.Nation')),
                ('member_ralation_one', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.Ralation')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='schoolrool.Schoolrool')),
            ],
        ),
    ]
