# Generated by Django 2.2.1 on 2019-08-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolrool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymembertwo',
            old_name='member_phtwo_two',
            new_name='member_phone_two',
        ),
    ]
