# Generated by Django 2.2.1 on 2019-08-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolrool', '0002_auto_20190825_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolrool',
            name='entrance_date',
            field=models.DateTimeField(),
        ),
    ]
