# Generated by Django 2.2.1 on 2019-08-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolrool', '0004_auto_20190825_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolrool',
            name='country_ID',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolrool',
            name='province_ID',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
